---
version: '2'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile

    ports:
      - "5432:5432" # Bind host port 5432 to PostgreSQL port 5432
    environment:
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_USER=canvas

  canvasd:
    build:
      context: .
      dockerfile: docker/canvas/Dockerfile
    ports:
      - "8080:8080"
      - "3000:3000"
    links:
      - db:db.local
